In [ ]:
import pandas as pd

# standings block

In [2]:
standings_df = pd.read_csv('lalig2_standings_2024.csv')
standings_df

,POSITION,CLUBS,MP,PTS,W-D-L,GF,GA,GD,HOME,AWAY
0,1,Levante,42,79,22-13-7,69,42,27,13-7-1,9-6-6
1,2,Elche,42,77,22-11-9,59,34,25,15-3-3,7-8-6
2,3,Real Oviedo,42,75,21-12-9,56,42,14,14-3-4,7-9-5
3,4,CD Mirandes,42,75,22-9-11,59,40,19,15-5-1,7-4-10
4,5,Racing Santander,42,71,20-11-11,65,51,14,11-6-4,9-5-7
5,6,Almeria,42,69,19-12-11,72,55,17,13-7-1,6-5-10
6,7,Granada,42,65,18-11-13,65,54,11,10-7-4,8-4-9
7,8,SD Huesca,42,64,18-10-14,58,49,9,12-5-4,6-5-10
8,9,Eibar,42,58,15-13-14,44,41,3,11-6-4,4-7-10
9,10,Albacete,42,58,15-13-14,57,57,0,11-6-4,4-7-10
10,11,Sporting Gijon,42,56,14-14-14,57,54,3,10-7-4,4-7-10
11,12,Burgos CF,42,55,15-10-17,41,48,-7,10-4-7,5-6-10
12,13,Cadiz,42,55,14-13-15,55,53,2,9-7-5,5-6-10
13,14,Cordoba,42,55,14-13-15,59,63,-4,8-8-5,6-5-10
14,15,Deportivo La Coruña,42,53,13-14-15,56,54,2,6-8-7,7-6-8
15,16,Malaga,42,53,12-17-13,42,46,-4,10-5-6,2-10-7
16,17,Castellon,42,53,14-11-17,65,63,2,9-5-7,5-6-10
17,18,Real Zaragoza,42,51,13-12-17,56,63,-7,7-7-7,6-5-10
18,19,Eldense,42,45,11-12-19,44,63,-19,6-7-8,5-5-11
19,20,Tenerife,42,36,8-12-22,35,55,-20,1-5-15,7-7-7
20,21,Racing de Ferrol,42,30,6-12-24,22,64,-42,3-5-13,3-7-11
21,22,Cartagena,42,23,6-5-31,33,78,-45,2-2-17,4-3-14

In [3]:
standings_df[['W', 'D', 'L']] = standings_df['W-D-L'].str.split('-', expand=True)
standings_df[['W', 'D', 'L']] = standings_df[['W', 'D', 'L']].astype(int)

standings_df = standings_df.drop(columns=['W-D-L'])

standings_df.head()

   POSITION             CLUBS  MP  PTS  GF  GA  GD    HOME    AWAY   W   D   L
0         1           Levante  42   79  69  42  27  13-7-1   9-6-6  22  13   7
1         2             Elche  42   77  59  34  25  15-3-3   7-8-6  22  11   9
2         3       Real Oviedo  42   75  56  42  14  14-3-4   7-9-5  21  12   9
3         4       CD Mirandes  42   75  59  40  19  15-5-1  7-4-10  22   9  11
4         5  Racing Santander  42   71  65  51  14  11-6-4   9-5-7  20  11  11

In [4]:
standings_df.rename(columns={'CLUBS':'team',
                             'POSITION': 'position',
                             'MP': 'matches_played',
                             "PTS": 'points',
                             "GF": 'goals_for',
                             "GA": 'goals_against',
                             "GD": 'goals_difference',
                             "HOME": 'home_record',
                             "AWAY": 'away_record'
                             }, 
                    inplace=True) 
standings_df

,position,team,matches_played,points,goals_for,goals_against,goals_difference,home_record,away_record,W,D,L
0,1,Levante,42,79,69,42,27,13-7-1,9-6-6,22,13,7
1,2,Elche,42,77,59,34,25,15-3-3,7-8-6,22,11,9
2,3,Real Oviedo,42,75,56,42,14,14-3-4,7-9-5,21,12,9
3,4,CD Mirandes,42,75,59,40,19,15-5-1,7-4-10,22,9,11
4,5,Racing Santander,42,71,65,51,14,11-6-4,9-5-7,20,11,11
5,6,Almeria,42,69,72,55,17,13-7-1,6-5-10,19,12,11
6,7,Granada,42,65,65,54,11,10-7-4,8-4-9,18,11,13
7,8,SD Huesca,42,64,58,49,9,12-5-4,6-5-10,18,10,14
8,9,Eibar,42,58,44,41,3,11-6-4,4-7-10,15,13,14
9,10,Albacete,42,58,57,57,0,11-6-4,4-7-10,15,13,14
10,11,Sporting Gijon,42,56,57,54,3,10-7-4,4-7-10,14,14,14
11,12,Burgos CF,42,55,41,48,-7,10-4-7,5-6-10,15,10,17
12,13,Cadiz,42,55,55,53,2,9-7-5,5-6-10,14,13,15
13,14,Cordoba,42,55,59,63,-4,8-8-5,6-5-10,14,13,15
14,15,Deportivo La Coruña,42,53,56,54,2,6-8-7,7-6-8,13,14,15
15,16,Malaga,42,53,42,46,-4,10-5-6,2-10-7,12,17,13
16,17,Castellon,42,53,65,63,2,9-5-7,5-6-10,14,11,17
17,18,Real Zaragoza,42,51,56,63,-7,7-7-7,6-5-10,13,12,17
18,19,Eldense,42,45,44,63,-19,6-7-8,5-5-11,11,12,19
19,20,Tenerife,42,36,35,55,-20,1-5-15,7-7-7,8,12,22
20,21,Racing de Ferrol,42,30,22,64,-42,3-5-13,3-7-11,6,12,24
21,22,Cartagena,42,23,33,78,-45,2-2-17,4-3-14,6,5,31

# goalkeeping cleaning

In [5]:
gk = pd.read_csv('laliga2_team_stats_goalkeeping_2024.csv')
gk

    POSITION             TEAMS  GP  GA    S  SOG   SV  CLR  CS
0          1         Cartagena  42  78  604  239  169    0   7
1          2            Málaga  42  46  459  189  150    0  16
2          3  Racing de Ferrol  42  64  468  201  138    0  14
3          4          Albacete  42  57  514  187  137    0  10
4          5      Racing Sant.  44  58  457  184  134    0  11
5          6         Deportivo  42  54  452  181  132    0  11
6          7    Sporting Gijón  42  54  440  184  132    0   9
7          8           Granada  42  54  423  182  131    0  12
8          9            Oviedo  46  46  399  174  131    0  16
9         10           Eldense  42  63  492  190  129    0  12
10        11           Almería  44  58  417  178  126    0  11
11        12            Huesca  42  49  471  165  120    0  11
12        13         Castellón  42  63  432  179  119    0   8
13        14             Cádiz  42  53  433  170  119    0  13
14        15             Eibar  42  41  398  151  114    0  14
15        16           Levante  42  42  458  150  111    0  11
16        17           Córdoba  42  63  401  164  107    0   9
17        18          Tenerife  42  55  386  158  106    0   9
18        19          Mirandés  46  47  436  146  104    0  17
19        20            Burgos  42  48  380  150  103    0  14
20        21             Elche  42  34  342  134   99    0  19
21        22          Zaragoza  42  63  432  161   99    0   8

In [6]:
gk.rename(columns={'TEAMS':'team',
                   'POSITION': 'position',
                             'GP': 'matches_played',
                             'GA': 'goals_against',
                             "S": 'shots',
                             "GD": 'goals_difference',
                             "SOG": 'shots_on_goal',
                             "SV": 'saves',
                             "CLR": "clearances",
                             "CS": 'clean_sheets'
                             }, 
                    inplace=True) 

gk.drop('clearances', axis=1, inplace=True)

gk

,position,team,matches_played,goals_against,shots,shots_on_goal,saves,clean_sheets
0,1,Cartagena,42,78,604,239,169,7
1,2,Málaga,42,46,459,189,150,16
2,3,Racing de Ferrol,42,64,468,201,138,14
3,4,Albacete,42,57,514,187,137,10
4,5,Racing Sant.,44,58,457,184,134,11
5,6,Deportivo,42,54,452,181,132,11
6,7,Sporting Gijón,42,54,440,184,132,9
7,8,Granada,42,54,423,182,131,12
8,9,Oviedo,46,46,399,174,131,16
9,10,Eldense,42,63,492,190,129,12
10,11,Almería,44,58,417,178,126,11
11,12,Huesca,42,49,471,165,120,11
12,13,Castellón,42,63,432,179,119,8
13,14,Cádiz,42,53,433,170,119,13
14,15,Eibar,42,41,398,151,114,14
15,16,Levante,42,42,458,150,111,11
16,17,Córdoba,42,63,401,164,107,9
17,18,Tenerife,42,55,386,158,106,9
18,19,Mirandés,46,47,436,146,104,17
19,20,Burgos,42,48,380,150,103,14
20,21,Elche,42,34,342,134,99,19
21,22,Zaragoza,42,63,432,161,99,8

# offensive block

In [7]:
off = pd.read_csv('laliga2_team_stats_offensive_2024.csv')
off

    POSITION             TEAMS  GP    S  SOG  SOP  SOFF  SAB  POSS   CK  OFF
0          1           Almería  44  600  224    6   263   58    53  228   47
1          2         Castellón  42  505  207    8   181   83    56  220  104
2          3      Racing Sant.  44  492  202    8   188   66    51  222   77
3          4           Córdoba  42  521  201    4   225   66    57  246   70
4          5          Mirandés  46  489  201    5   184   83    46  203   63
5          6             Elche  42  470  199    2   186   50    61  208   60
6          7           Levante  42  470  193    4   178   66    49  201   79
7          8          Zaragoza  42  475  191    5   201   46    51  197   72
8          9          Albacete  42  442  182    4   182   53    45  189   76
9         10            Oviedo  46  478  180    4   209   70    52  208   70
10        11             Eibar  42  444  179    1   181   64    51  195   71
11        12    Sporting Gijón  42  438  179    5   172   57    50  199   58
12        13         Deportivo  42  433  177    5   164   67    53  213   61
13        14           Granada  42  459  176    5   185   70    51  201   55
14        15             Cádiz  42  396  166    1   166   33    50  157   67
15        16            Burgos  42  373  161    4   150   38    48  184   75
16        17           Eldense  42  423  151    4   191   55    45  225   65
17        18            Málaga  42  387  143    5   173   33    52  193   69
18        19            Huesca  42  349  142    4   150   44    44  173   55
19        20          Tenerife  42  400  132    0   191   60    48  178   98
20        21         Cartagena  42  291  119    7   117   38    40  146   90
21        22  Racing de Ferrol  42  359  112    3   166   62    47  179   79

In [8]:
off.rename(columns={'TEAMS':'team',
                    'POSITION': 'position',
                             'GP': 'matches_played',
                             "S": 'shots',
                             "SOG": 'shots_on_goal',
                             'SOP': "shots_on_posts",
                             "SOFF": "shots_off_target",
                             "SAB": "shot_attempts_blocked",
                             "POSS": "possession_time_min_avg",
                             "CK": "corner_kicks",
                             "OFF": "offsides"
                             }, 
                    inplace=True)

In [9]:
off

,position,team,matches_played,shots,shots_on_goal,shots_on_posts,shots_off_target,shot_attempts_blocked,possession_time_min_avg,corner_kicks,offsides
0,1,Almería,44,600,224,6,263,58,53,228,47
1,2,Castellón,42,505,207,8,181,83,56,220,104
2,3,Racing Sant.,44,492,202,8,188,66,51,222,77
3,4,Córdoba,42,521,201,4,225,66,57,246,70
4,5,Mirandés,46,489,201,5,184,83,46,203,63
5,6,Elche,42,470,199,2,186,50,61,208,60
6,7,Levante,42,470,193,4,178,66,49,201,79
7,8,Zaragoza,42,475,191,5,201,46,51,197,72
8,9,Albacete,42,442,182,4,182,53,45,189,76
9,10,Oviedo,46,478,180,4,209,70,52,208,70
10,11,Eibar,42,444,179,1,181,64,51,195,71
11,12,Sporting Gijón,42,438,179,5,172,57,50,199,58
12,13,Deportivo,42,433,177,5,164,67,53,213,61
13,14,Granada,42,459,176,5,185,70,51,201,55
14,15,Cádiz,42,396,166,1,166,33,50,157,67
15,16,Burgos,42,373,161,4,150,38,48,184,75
16,17,Eldense,42,423,151,4,191,55,45,225,65
17,18,Málaga,42,387,143,5,173,33,52,193,69
18,19,Huesca,42,349,142,4,150,44,44,173,55
19,20,Tenerife,42,400,132,0,191,60,48,178,98
20,21,Cartagena,42,291,119,7,117,38,40,146,90
21,22,Racing de Ferrol,42,359,112,3,166,62,47,179,79

# standard cleaning

In [10]:
standard= pd.read_csv('laliga2_team_stats_standard_2024.csv')
standard

,POSITION,TEAMS,GP,GF,KG,HG,1G,2G,GA,1GC,2GC,A,YC,RC,YRC
0,1,Almería,44,74,67,6,29,45,58,28,30,42,108,5,2
1,2,Levante,42,69,58,9,28,41,42,16,26,41,83,0,1
2,3,Racing Sant.,44,69,58,10,31,38,58,21,37,46,108,2,3
3,4,Mirandés,46,68,54,11,29,39,47,20,26,43,97,6,1
4,5,Castellón,42,65,53,10,31,34,63,31,32,40,88,2,2
5,6,Granada,42,65,55,8,28,37,54,19,35,43,108,6,2
6,7,Oviedo,46,62,44,16,25,36,46,26,20,38,114,2,0
7,8,Córdoba,42,59,49,8,22,37,63,26,37,37,130,6,1
8,9,Elche,42,59,45,14,27,32,34,15,19,41,90,2,3
9,10,Huesca,42,58,49,7,22,36,49,23,26,29,100,7,2
10,11,Albacete,42,57,49,6,28,29,57,25,32,24,73,6,1
11,12,Sporting Gijón,42,57,49,5,23,34,54,20,34,31,100,2,1
12,13,Deportivo,42,56,50,5,21,35,54,28,26,34,66,4,1
13,14,Zaragoza,42,56,44,10,17,39,63,30,33,38,120,4,2
14,15,Cádiz,42,55,44,11,27,28,53,18,35,36,109,3,4
15,16,Eibar,42,44,35,6,23,21,41,14,27,31,101,1,6
16,17,Eldense,42,44,35,9,18,26,63,25,38,26,106,4,2
17,18,Málaga,42,42,34,6,16,26,46,16,30,26,94,5,0
18,19,Burgos,42,41,37,4,17,24,48,18,30,27,106,1,1
19,20,Tenerife,42,35,21,12,14,21,55,18,37,30,95,7,2
20,21,Cartagena,42,33,28,4,17,16,78,36,42,18,99,1,0
21,22,Racing de Ferrol,42,22,17,4,9,13,64,29,35,11,82,4,2

In [13]:
standard.rename(columns={'TEAMS':'team',
                    'POSITION': 'position',
                             'GP': 'matches_played',
                             'GF': 'goals_for',
                             'KG': 'kicked_goals',
                             'HG': 'header_goals',
                             '1G': 'first_half_goals',
                             '2G': 'second_half_goals',
                             'GA': 'goals_against',
                             '1GC': 'goals_against_first_half',
                             '2GC': 'goals_against_second_half',
                             'A': 'assists',
                             'YC': "yellow_cards",
                             "RC": 'red_cards',
                             }, 
                    inplace=True) 

standard.drop('YRC', axis=1, inplace=True)

In [14]:
standard

,position,team,matches_played,goals_for,kicked_goals,header_goals,first_half_goals,second_half_goals,goals_against,goals_against_first_half,goals_against_second_half,assists,yellow_cards,red_cards
0,1,Almería,44,74,67,6,29,45,58,28,30,42,108,5
1,2,Levante,42,69,58,9,28,41,42,16,26,41,83,0
2,3,Racing Sant.,44,69,58,10,31,38,58,21,37,46,108,2
3,4,Mirandés,46,68,54,11,29,39,47,20,26,43,97,6
4,5,Castellón,42,65,53,10,31,34,63,31,32,40,88,2
5,6,Granada,42,65,55,8,28,37,54,19,35,43,108,6
6,7,Oviedo,46,62,44,16,25,36,46,26,20,38,114,2
7,8,Córdoba,42,59,49,8,22,37,63,26,37,37,130,6
8,9,Elche,42,59,45,14,27,32,34,15,19,41,90,2
9,10,Huesca,42,58,49,7,22,36,49,23,26,29,100,7
10,11,Albacete,42,57,49,6,28,29,57,25,32,24,73,6
11,12,Sporting Gijón,42,57,49,5,23,34,54,20,34,31,100,2
12,13,Deportivo,42,56,50,5,21,35,54,28,26,34,66,4
13,14,Zaragoza,42,56,44,10,17,39,63,30,33,38,120,4
14,15,Cádiz,42,55,44,11,27,28,53,18,35,36,109,3
15,16,Eibar,42,44,35,6,23,21,41,14,27,31,101,1
16,17,Eldense,42,44,35,9,18,26,63,25,38,26,106,4
17,18,Málaga,42,42,34,6,16,26,46,16,30,26,94,5
18,19,Burgos,42,41,37,4,17,24,48,18,30,27,106,1
19,20,Tenerife,42,35,21,12,14,21,55,18,37,30,95,7
20,21,Cartagena,42,33,28,4,17,16,78,36,42,18,99,1
21,22,Racing de Ferrol,42,22,17,4,9,13,64,29,35,11,82,4