In [11]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

import pandas as pd

In [2]:
website = 'https://www.foxsports.com/soccer/laliga-2/standings'

In [3]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get(website)

# grabbing headers for later use

In [4]:
headers_tag = driver.find_element(By.XPATH, "//thead[@class='data-header fs-11 ls-pt25']")
headers_tag

In [5]:
list_headers = headers_tag.find_elements(By.TAG_NAME, "th")
list_headers

[<selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.80")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.81")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.84")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.85")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.86")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.87")>,
 <selenium.webdriver.remote.webelement.WebElement (session="62af0ed4c58ca45b4c4b4e262b1b97e2", element="f.6BD9D4F18B440E3A82EA9218405B672A.d.7CB304978127208E29A243D770E80C00.e.88")>]

In [6]:
len(list_headers)

9

In [ ]:
headers = []

for head in list_headers:
    text = head.text
    headers.append(text)

headers

['CLUBS', 'MP', 'PTS', 'W-D-L', 'GF', 'GA', 'GD', 'HOME', 'AWAY']

In [13]:
headers.insert(0, 'POSITION')

In [14]:
headers

['POSITION', 'CLUBS', 'MP', 'PTS', 'W-D-L', 'GF', 'GA', 'GD', 'HOME', 'AWAY']

# first will grab standings

In [8]:
team_rows = driver.find_elements(By.XPATH, '//tr[starts-with(@id, "tbl-row-")]')

# Now you can loop through them safely!
for row in team_rows:
    print(row.text)
    print("-" * 20)

1
Racing Sant.
42
82
25-7-10
90
61
29
15-2-4
10-5-6
--------------------
2
Deportivo
42
77
22-11-9
65
44
21
11-5-5
11-6-4
--------------------
3
Almería
42
74
22-8-12
81
63
18
15-2-4
7-6-8
--------------------
4
Málaga
42
73
21-10-11
75
52
23
12-7-2
9-3-9
--------------------
5
Las Palmas
42
73
20-13-9
57
40
17
12-6-3
8-7-6
--------------------
6
Castellón
42
72
20-12-10
70
51
19
13-4-4
7-8-6
--------------------
7
Burgos
42
72
20-12-10
48
33
15
10-8-3
10-4-7
--------------------
8
Eibar
42
67
19-10-13
52
40
12
14-4-3
5-6-10
--------------------
9
Córdoba
42
61
17-10-15
57
61
-4
9-5-7
8-5-8
--------------------
10
Sporting Gijón
42
61
18-7-17
60
54
6
11-6-4
7-1-13
--------------------
11
AD Ceuta FC
42
61
17-10-15
51
63
-12
12-4-5
5-6-10
--------------------
12
Albacete
42
59
16-11-15
56
55
1
9-4-8
7-7-7
--------------------
13
FC Andorra
42
58
16-10-16
62
54
8
8-6-7
8-4-9
--------------------
14
Granada
42
48
12-12-18
50
56
-6
6-8-7
6-4-11
--------------------
15
Real Sociedad San Sebastian B
42
47
12-11-19
52
61
-9
7-8-6
5-3-13
--------------------
16
Leganes
42
46
11-13-18
43
51
-8
7-6-8
4-7-10
--------------------
17
Valladolid
42
46
12-10-20
44
57
-13
8-5-8
4-5-12
--------------------
18
Cádiz
42
43
11-10-21
41
61
-20
7-2-12
4-8-9
--------------------
19
Mirandés
42
40
10-10-22
47
69
-22
6-5-10
4-5-12
--------------------
20
Huesca
42
38
9-11-22
41
63
-22
7-7-7
2-4-15
--------------------
21
Cultural Leonesa
42
37
9-10-23
39
68
-29
4-5-12
5-5-11
--------------------
22
Zaragoza
42
36
8-12-22
35
59
-24
4-6-11
4-6-11
--------------------

# create the csv for the standings data

In [ ]:
all_team_data = []

for row in team_rows:
    row_cells = row.text.split('\n')
    row_cells = [cell.strip() for cell in row_cells if cell.strip()]
    
    all_team_data.append(row_cells)

['1',
 'Racing Sant.',
 '42',
 '82',
 '25-7-10',
 '90',
 '61',
 '29',
 '15-2-4',
 '10-5-6']

In [10]:
all_team_data[0]

['1',
 'Racing Sant.',
 '42',
 '82',
 '25-7-10',
 '90',
 '61',
 '29',
 '15-2-4',
 '10-5-6']

In [ ]:
df = pd.DataFrame(all_team_data, columns=headers)
df.head()

  POSITION         CLUBS  MP PTS     W-D-L  GF  GA  GD    HOME    AWAY
0        1  Racing Sant.  42  82   25-7-10  90  61  29  15-2-4  10-5-6
1        2     Deportivo  42  77   22-11-9  65  44  21  11-5-5  11-6-4
2        3       Almería  42  74   22-8-12  81  63  18  15-2-4   7-6-8
3        4        Málaga  42  73  21-10-11  75  52  23  12-7-2   9-3-9
4        5    Las Palmas  42  73   20-13-9  57  40  17  12-6-3   8-7-6

## save to csv file

### can clean it up later

In [17]:
df.to_csv("laliga2_standings.csv", index=False)
print("created standings data")

created standings data

# more advanced stats

In [18]:
base_url = "https://www.foxsports.com"
stat_urls = {
    "standard": "https://www.foxsports.com/soccer/laliga-2/team-stats?category=standard&season=2025&groupId=129",
    "offensive": base_url + "/soccer/laliga-2/team-stats?category=offensive&season=2025&groupId=129",
    "defensive": base_url + "/soccer/laliga-2/team-stats?category=defensive&season=2025&groupId=129",
    "goalkeeping": base_url + "/soccer/laliga-2/team-stats?category=goalkeeping&season=2025&groupId=129"
}

In [19]:
import time

In [ ]:
all_stat_tables = {}

for cat_name, url in stat_urls.items():
    print(f"{cat_name.upper()} stats page...")
    driver.get(url)
    time.sleep(1.5)
    
    # headers
    headers_tag = driver.find_element(By.XPATH, "//thead[@class='data-header fs-11 ls-pt25 sticky-row-wrapper']")
    list_headers = [head.text.strip() for head in headers_tag.find_elements(By.TAG_NAME, "th") if head.text.strip()]
    list_headers.insert(0, "POSITION")
    
    # team rows
    team_rows = driver.find_elements(By.XPATH, '//tr[starts-with(@id, "tbl-row-")]')
    
    # extract text
    cat_data = []
    for row in team_rows:
        row_cells = [cell.strip() for cell in row.text.split('\n') if cell.strip()]
        if row_cells:
            cat_data.append(row_cells)
                
    # create dataframe
    df_cat = pd.DataFrame(cat_data, columns=list_headers)
    all_stat_tables[cat_name] = df_cat
    
    print(f"Successfully saved {cat_name} to data dictionary!\n" + "-"*30)

print("All categories scraped successfully!")

Navigating to STANDARD stats page...
Found 15 headers and 22 team rows.
Successfully saved standard to data dictionary!
------------------------------
Navigating to OFFENSIVE stats page...
Found 11 headers and 22 team rows.
Successfully saved offensive to data dictionary!
------------------------------
Navigating to DEFENSIVE stats page...
Found 5 headers and 22 team rows.
Successfully saved defensive to data dictionary!
------------------------------
Navigating to GOALKEEPING stats page...
Found 9 headers and 22 team rows.
Successfully saved goalkeeping to data dictionary!
------------------------------
All categories scraped successfully!

### invidivudal pieces

In [31]:
df_cat

   POSITION                          TEAMS  GP  GA    S  SOG   SV CLR  CS
0         1                        Almería  43  64  499  212  153   0   9
1         2                    AD Ceuta FC  42  63  470  206  146   0  12
2         3                       Mirandés  42  69  527  205  145   0   3
3         4                         Málaga  43  52  483  192  144   0  12
4         5                       Zaragoza  42  59  462  195  143   0   8
5         6                         Huesca  42  63  477  200  140   0   9
6         7                        Leganes  42  51  465  187  137   0  13
7         8                          Cádiz  42  61  539  190  133   0  11
8         9                     FC Andorra  42  54  442  185  133   0   9
9        10                   Racing Sant.  42  61  481  191  133   0   8
10       11                        Córdoba  42  61  421  190  132   0   9
11       12                       Albacete  42  55  488  180  127   0  13
12       13                          Eibar  42  40  450  165  127   0  18
13       14                 Sporting Gijón  42  54  470  177  127   0  11
14       15  Real Sociedad San Sebastian B  42  61  520  188  126   0  10
15       16               Cultural Leonesa  42  68  452  188  124   0   7
16       17                        Granada  42  56  446  175  120   0  12
17       18                      Castellón  43  52  368  167  118   0  12
18       19                      Deportivo  42  44  439  155  116   0  11
19       20                     Las Palmas  43  41  416  152  116   0  14
20       21                         Burgos  42  33  396  143  113   0  19
21       22                     Valladolid  42  57  384  166  111   0  11

In [30]:
cat_data[0]

['1', 'Almería', '43', '64', '499', '212', '153', '0', '9']

## all together (specify standard, offensive, defensive, goalkeeping)

In [27]:
all_stat_tables['standard']

,POSITION,TEAMS,GP,GF,KG,HG,1G,2G,GA,1GC,2GC,A,YC,RC,YRC
0,1,Racing Sant.,42,90,78,12,36,54,61,28,33,58,114,5,1
1,2,Almería,43,82,74,7,36,45,64,23,40,47,114,4,2
2,3,Málaga,43,76,67,9,33,43,52,17,35,45,94,6,1
3,4,Castellón,43,71,60,11,35,36,52,20,32,47,113,5,6
4,5,Deportivo,42,65,58,4,28,37,44,22,22,38,103,1,1
5,6,FC Andorra,42,62,53,6,25,37,54,22,32,39,111,2,1
6,7,Sporting Gijón,42,60,48,11,28,32,54,23,31,33,100,5,2
7,8,Córdoba,42,57,47,6,21,36,61,32,29,33,110,3,1
8,9,Las Palmas,43,57,52,5,30,27,41,16,25,44,75,3,2
9,10,Albacete,42,56,39,15,20,36,55,24,31,32,87,4,0
10,11,Eibar,42,52,42,9,23,29,40,19,21,28,104,3,0
11,12,Real Sociedad San Sebastian B,42,52,43,6,21,31,61,29,32,26,132,2,3
12,13,AD Ceuta FC,42,51,39,8,29,21,63,31,31,29,109,3,2
13,14,Granada,42,50,40,10,31,19,56,26,30,34,105,6,2
14,15,Burgos,42,48,41,7,24,24,33,17,16,24,105,1,1
15,16,Mirandés,42,47,35,11,21,26,69,32,37,33,120,3,4
16,17,Valladolid,42,44,30,13,21,23,57,26,31,26,114,3,5
17,18,Leganes,42,43,36,6,16,27,51,20,31,25,120,4,2
18,19,Cádiz,42,41,36,3,17,24,61,31,30,31,116,3,1
19,20,Huesca,42,41,29,11,15,26,63,28,35,25,103,6,1
20,21,Cultural Leonesa,42,39,35,3,19,20,68,33,35,25,94,4,2
21,22,Zaragoza,42,35,31,2,13,22,59,23,36,15,123,9,5

In [28]:
all_stat_tables['offensive']

,POSITION,TEAMS,GP,S,SOG,SOP,SOFF,SAB,POSS,CK,OFF
0,1,Almería,43,600,246,3,234,68,52,204,66
1,2,Racing Sant.,42,518,241,3,187,60,51,238,78
2,3,Málaga,43,518,237,1,176,78,53,180,57
3,4,Castellón,43,557,220,4,208,93,55,270,84
4,5,Córdoba,42,573,217,12,233,67,58,268,93
5,6,FC Andorra,42,534,206,3,205,71,60,205,60
6,7,Las Palmas,43,473,194,7,163,80,56,188,92
7,8,Deportivo,42,488,190,6,197,68,51,210,72
8,9,Sporting Gijón,42,423,184,1,157,37,45,192,79
9,10,Real Sociedad San Sebastian B,42,471,182,6,198,56,44,159,63
10,11,Albacete,42,453,181,6,190,53,43,214,52
11,12,Leganes,42,457,179,4,186,46,50,197,70
12,13,Cultural Leonesa,42,433,178,8,180,43,49,164,51
13,14,Mirandés,42,437,178,8,180,50,44,183,70
14,15,Eibar,42,414,167,1,157,63,49,182,67
15,16,Granada,42,433,162,4,183,63,49,182,75
16,17,Valladolid,42,426,160,5,185,51,50,224,73
17,18,AD Ceuta FC,42,377,154,5,147,54,51,172,61
18,19,Zaragoza,42,432,150,4,178,70,48,210,63
19,20,Burgos,42,357,136,2,161,38,48,156,79
20,21,Huesca,42,394,136,1,174,52,46,190,69
21,22,Cádiz,42,370,128,3,174,49,47,185,67

In [39]:
for x, y in all_stat_tables.items():
    print(x)
    print(y)
    print('---' * 50)

standard
   POSITION                          TEAMS  GP  GF  KG  HG  1G  2G  GA 1GC  \
0         1                   Racing Sant.  42  90  78  12  36  54  61  28
1         2                        Almería  43  82  74   7  36  45  64  23
2         3                         Málaga  43  76  67   9  33  43  52  17
3         4                      Castellón  43  71  60  11  35  36  52  20
4         5                      Deportivo  42  65  58   4  28  37  44  22
5         6                     FC Andorra  42  62  53   6  25  37  54  22
6         7                 Sporting Gijón  42  60  48  11  28  32  54  23
7         8                        Córdoba  42  57  47   6  21  36  61  32
8         9                     Las Palmas  43  57  52   5  30  27  41  16
9        10                       Albacete  42  56  39  15  20  36  55  24
10       11                          Eibar  42  52  42   9  23  29  40  19
11       12  Real Sociedad San Sebastian B  42  52  43   6  21  31  61  29
12       13                    AD Ceuta FC  42  51  39   8  29  21  63  31
13       14                        Granada  42  50  40  10  31  19  56  26
14       15                         Burgos  42  48  41   7  24  24  33  17
15       16                       Mirandés  42  47  35  11  21  26  69  32
16       17                     Valladolid  42  44  30  13  21  23  57  26
17       18                        Leganes  42  43  36   6  16  27  51  20
18       19                          Cádiz  42  41  36   3  17  24  61  31
19       20                         Huesca  42  41  29  11  15  26  63  28
20       21               Cultural Leonesa  42  39  35   3  19  20  68  33
21       22                       Zaragoza  42  35  31   2  13  22  59  23

   2GC   A   YC RC YRC
0   33  58  114  5   1
1   40  47  114  4   2
2   35  45   94  6   1
3   32  47  113  5   6
4   22  38  103  1   1
5   32  39  111  2   1
6   31  33  100  5   2
7   29  33  110  3   1
8   25  44   75  3   2
9   31  32   87  4   0
10  21  28  104  3   0
11  32  26  132  2   3
12  31  29  109  3   2
13  30  34  105  6   2
14  16  24  105  1   1
15  37  33  120  3   4
16  31  26  114  3   5
17  31  25  120  4   2
18  30  31  116  3   1
19  35  25  103  6   1
20  35  25   94  4   2
21  36  15  123  9   5
------------------------------------------------------------------------------------------------------------------------------------------------------
offensive
   POSITION                          TEAMS  GP    S  SOG SOP SOFF SAB POSS  \
0         1                        Almería  43  600  246   3  234  68   52
1         2                   Racing Sant.  42  518  241   3  187  60   51
2         3                         Málaga  43  518  237   1  176  78   53
3         4                      Castellón  43  557  220   4  208  93   55
4         5                        Córdoba  42  573  217  12  233  67   58
5         6                     FC Andorra  42  534  206   3  205  71   60
6         7                     Las Palmas  43  473  194   7  163  80   56
7         8                      Deportivo  42  488  190   6  197  68   51
8         9                 Sporting Gijón  42  423  184   1  157  37   45
9        10  Real Sociedad San Sebastian B  42  471  182   6  198  56   44
10       11                       Albacete  42  453  181   6  190  53   43
11       12                        Leganes  42  457  179   4  186  46   50
12       13               Cultural Leonesa  42  433  178   8  180  43   49
13       14                       Mirandés  42  437  178   8  180  50   44
14       15                          Eibar  42  414  167   1  157  63   49
15       16                        Granada  42  433  162   4  183  63   49
16       17                     Valladolid  42  426  160   5  185  51   50
17       18                    AD Ceuta FC  42  377  154   5  147  54   51
18       19                       Zaragoza  42  432  150   4  178  70   48
19       20                         Burgos  42  357  136   2  161  38   48
20       21                         Huesca  42  394  136   1  174  52   46
21       22                          Cádiz  42  370  128   3  174  49   47

     CK OFF
0   204  66
1   238  78
2   180  57
3   270  84
4   268  93
5   205  60
6   188  92
7   210  72
8   192  79
9   159  63
10  214  52
11  197  70
12  164  51
13  183  70
14  182  67
15  182  75
16  224  73
17  172  61
18  210  63
19  156  79
20  190  69
21  185  67
------------------------------------------------------------------------------------------------------------------------------------------------------
defensive
   POSITION                          TEAMS  GP   FK OG
0         1                    AD Ceuta FC  42  156  1
1         2                       Albacete  42  219  1
2         3                        Almería  43   62  1
3         4                         Burgos  42   72  2
4         5                      Castellón  43  135  0
5         6               Cultural Leonesa  42  251  3
6         7                          Cádiz  42   27  3
7         8                        Córdoba  42  123  2
8         9                      Deportivo  42   10  1
9        10                          Eibar  42    3  0
10       11                     FC Andorra  42  123  2
11       12                        Granada  42  113  2
12       13                         Huesca  42   40  1
13       14                     Las Palmas  43  245  3
14       15                        Leganes  42  122  2
15       16                       Mirandés  42   64  3
16       17                         Málaga  43   68  3
17       18                   Racing Sant.  42  205  2
18       19  Real Sociedad San Sebastian B  42   21  2
19       20                 Sporting Gijón  42  196  2
20       21                     Valladolid  42   17  2
21       22                       Zaragoza  42  177  3
------------------------------------------------------------------------------------------------------------------------------------------------------
goalkeeping
   POSITION                          TEAMS  GP  GA    S  SOG   SV CLR  CS
0         1                        Almería  43  64  499  212  153   0   9
1         2                    AD Ceuta FC  42  63  470  206  146   0  12
2         3                       Mirandés  42  69  527  205  145   0   3
3         4                         Málaga  43  52  483  192  144   0  12
4         5                       Zaragoza  42  59  462  195  143   0   8
5         6                         Huesca  42  63  477  200  140   0   9
6         7                        Leganes  42  51  465  187  137   0  13
7         8                          Cádiz  42  61  539  190  133   0  11
8         9                     FC Andorra  42  54  442  185  133   0   9
9        10                   Racing Sant.  42  61  481  191  133   0   8
10       11                        Córdoba  42  61  421  190  132   0   9
11       12                       Albacete  42  55  488  180  127   0  13
12       13                          Eibar  42  40  450  165  127   0  18
13       14                 Sporting Gijón  42  54  470  177  127   0  11
14       15  Real Sociedad San Sebastian B  42  61  520  188  126   0  10
15       16               Cultural Leonesa  42  68  452  188  124   0   7
16       17                        Granada  42  56  446  175  120   0  12
17       18                      Castellón  43  52  368  167  118   0  12
18       19                      Deportivo  42  44  439  155  116   0  11
19       20                     Las Palmas  43  41  416  152  116   0  14
20       21                         Burgos  42  33  396  143  113   0  19
21       22                     Valladolid  42  57  384  166  111   0  11
------------------------------------------------------------------------------------------------------------------------------------------------------

# csv files for each of the catagories

In [40]:
for cat_name, df_table in all_stat_tables.items():
    filename = f"laliga2_team_stats_{cat_name}.csv"
    
    df_table.to_csv(filename, index=False)